openapi: 3.2.0
info:
  description: Pricefinder API provides access to property, sale and listing searches as well as suburb statistics and SSO to the Pricefinder website capabilities.
  version: 1.13.1
  title: PriceFinder API v1.13.1 Events API
  contact:
    name: Pricefinder
  license:
    name: Terms and Conditions
    url: https://www.domain.com.au/group/api-terms-and-conditions/
servers:
- url: /v1
tags:
- name: Events
paths:
  /events/cmaEvent/{cmaId}:
    post:
      tags:
      - Events
      description: ''
      operationId: saveEvent
      parameters:
      - name: cmaId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventParameters'
      summary: Save event
      x-summary-source: derived
components:
  schemas:
    EventParameters:
      type: object
      properties:
        cmaId:
          type: integer
          format: int64
        eventType:
          type: string
        eventDetails:
          type: object
