openapi: 3.2.0
info:
  description: Pricefinder API provides access to property, sale and listing searches as well as suburb statistics and SSO to the Pricefinder website capabilities.
  version: 1.13.1
  title: PriceFinder API v1.13.1 SSO API
  contact:
    name: Pricefinder
  license:
    name: Terms and Conditions
    url: https://www.domain.com.au/group/api-terms-and-conditions/
servers:
- url: /v1
tags:
- name: SSO
paths:
  /sso:
    get:
      tags:
      - SSO
      description: ''
      operationId: home
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Home
      x-summary-source: derived
  /sso/properties/{propertyId}:
    get:
      tags:
      - SSO
      description: ''
      operationId: property
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Property
      x-summary-source: derived
  /sso/properties/{propertyId}/appraisals/rentalcma:
    get:
      tags:
      - SSO
      description: ''
      operationId: appraisalsRentalCma
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Appraisals rental cma
      x-summary-source: derived
  /sso/properties/{propertyId}/appraisals/salecma:
    get:
      tags:
      - SSO
      description: ''
      operationId: appraisalsSaleCma
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Appraisals sale cma
      x-summary-source: derived
  /sso/properties/{propertyId}/appraisals/soi:
    get:
      tags:
      - SSO
      description: ''
      operationId: appraisalsSoi
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Appraisals soi
      x-summary-source: derived
  /sso/properties/{propertyId}/cma:
    get:
      tags:
      - SSO
      description: ''
      operationId: cma
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      deprecated: true
      summary: Cma
      x-summary-source: derived
  /sso/properties/{propertyId}/pricefinder:
    get:
      tags:
      - SSO
      description: ''
      operationId: propertyPricefinder
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Property pricefinder
      x-summary-source: derived
  /sso/properties/{propertyId}/radial/sales:
    get:
      tags:
      - SSO
      description: ''
      operationId: radialSales
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Radial sales
      x-summary-source: derived
  /sso/properties/{propertyId}/titles:
    get:
      tags:
      - SSO
      description: ''
      operationId: titles
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SSOLink'
      summary: Titles
      x-summary-source: derived
components:
  schemas:
    SSOLink:
      type: object
      properties:
        link:
          type: string
