openapi: 3.2.0
info:
  description: Pricefinder API provides access to property, sale and listing searches as well as suburb statistics and SSO to the Pricefinder website capabilities.
  version: 1.13.1
  title: PriceFinder API v1.13.1 Subscriptions API
  contact:
    name: Pricefinder
  license:
    name: Terms and Conditions
    url: https://www.domain.com.au/group/api-terms-and-conditions/
servers:
- url: /v1
tags:
- name: Subscriptions
paths:
  /eventsubscriptions/currentuser:
    get:
      tags:
      - Subscriptions
      description: ''
      operationId: userEventsSubscription
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PropertyEventSubscription'
      summary: User events subscription
      x-summary-source: derived
  /eventsubscriptions/properties:
    post:
      tags:
      - Subscriptions
      summary: Properties events subscribe
      description: 'Subscribe to property event alerts (currently only available through email notifications) for those properties.

        Note: This endpoint is NOT additive

        i.e. Multiple calls to this endpoint on the same property will keep overwriting the subscription with the eventTypes passed in the latest request.

        Example :


        Subscribe to property X for ''ForSale'' event


        Subscribe to property X for ''ForRent'' event


        After these 2 calls X is only subscribed for ''ForRent'''
      operationId: propertiesEventsSubscribe
      parameters:
      - name: propertyIds
        in: query
        description: The available eventTypes are <b>ForSale</b>, <b>ForRent</b> and <b>Sold</b>. They are case sensitive.
        required: false
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: integer
            format: int64
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventSubcriptionParameters'
      x-summary-source: derived
  /eventsubscriptions/property/{propertyId}:
    get:
      tags:
      - Subscriptions
      description: ''
      operationId: propertyEventSubscription
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: The request has succeeded with event subscriptions available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropertyEventSubscription'
        '204':
          description: The request has succeeded but no events subscribed
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      summary: Property event subscription
      x-summary-source: derived
    post:
      tags:
      - Subscriptions
      summary: Property events subscribe
      description: 'Subscribe to property event alerts (currently only available through email notifications) for this property.

        Note: This endpoint is NOT additive

        i.e. Multiple calls to this endpoint on the same property will keep overwriting the subscription with the eventTypes passed in the latest request.

        Example :


        Subscribe to property X for ''ForSale'' event


        Subscribe to property X for ''ForRent'' event


        After these 2 calls X is only subscribed for ''ForRent'''
      operationId: propertyEventsSubscribe
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventSubcriptionParameters'
        description: The available eventTypes are <b>ForSale</b>, <b>ForRent</b> and <b>Sold</b>. They are case sensitive.
      x-summary-source: derived
    delete:
      tags:
      - Subscriptions
      description: ''
      operationId: propertyEventsUnSubscribe
      parameters:
      - name: propertyId
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
      summary: Property events un subscribe
      x-summary-source: derived
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
    PropertyEventSubscription:
      type: object
      properties:
        propertyId:
          type: integer
          format: int64
        subscriptionDate:
          type: string
          format: date-time
        eventTypes:
          type: array
          items:
            $ref: '#/components/schemas/PropertyEventType'
    EventSubcriptionParameters:
      type: object
      properties:
        eventTypes:
          type: array
          items:
            type: string
            enum:
            - ForRent
            - ForSale
            - SoldVerified
            - Sold
    PropertyEventType:
      type: object
      properties:
        display:
          type: string
        key:
          type: string
