openapi: 3.2.0
info:
  description: Pricefinder API provides access to property, sale and listing searches as well as suburb statistics and SSO to the Pricefinder website capabilities.
  version: 1.13.1
  title: PriceFinder API v1.13.1 Features API
  contact:
    name: Pricefinder
  license:
    name: Terms and Conditions
    url: https://www.domain.com.au/group/api-terms-and-conditions/
servers:
- url: /v1
tags:
- name: Features
paths:
  /features:
    get:
      tags:
      - Features
      description: ''
      operationId: getFeatures
      responses:
        '200':
          description: successful operation
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserFeatures'
      summary: Get features
      x-summary-source: derived
components:
  schemas:
    Feature:
      type: object
      properties:
        feature:
          type: string
        hasAccess:
          type: boolean
    UserFeatures:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
