openapi: 3.2.0
info:
  description: Pricefinder API provides access to property, sale and listing searches as well as suburb statistics and SSO to the Pricefinder website capabilities.
  version: 1.13.1
  title: PriceFinder API v1.13.1 Images API
  contact:
    name: Pricefinder
  license:
    name: Terms and Conditions
    url: https://www.domain.com.au/group/api-terms-and-conditions/
servers:
- url: /v1
tags:
- name: Images
paths:
  /images/{id}:
    get:
      tags:
      - Images
      description: 'You can access this method in an image tag by appending your access_token to the query string

        ie /v1/image/1?access_token=123abc'
      operationId: image
      parameters:
      - name: id
        in: path
        required: true
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      - name: height
        in: query
        required: false
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      - name: width
        in: query
        required: false
        pds:
          hidden: false
          extra: false
          enumerate: false
          deprecated: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: successful operation
      summary: Image
      x-summary-source: derived
